<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
		            ->createQuery(
		                'SELECT p FROM AppBundle:Category p ORDER BY p.Name'
		            )
		            ->getResult();
    } 
}
