# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt
            
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            form_login: 
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                #login_path: user_login
                #check_path: user_login
            
            logout: true
            anonymous: true
                
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            pattern:    ^/

    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
