<?php

namespace AppBundle\Entity;

/**
 * DeliveryPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryPointRepository extends \Doctrine\ORM\EntityRepository
{
}
