<?php

namespace AppBundle\Entity;

/**
 * DeliveryStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryStateRepository extends \Doctrine\ORM\EntityRepository
{
}
