<?php

namespace AppBundle\Entity;

/**
 * OrderElemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderElemsRepository extends \Doctrine\ORM\EntityRepository
{
}
