<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStateRepository extends \Doctrine\ORM\EntityRepository
{
	public function findOneByName($stateName)
	{
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT p FROM AppBundle:OrderState p
	            WHERE p.Name = :Name'
	        )->setParameter('Name', $stateName);

	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
