<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
	{
		return $this->getEntityManager()
					->createQuery(
						'SELECT p FROM AppBundle:Product p ORDER BY p.Name ASC'
					)
					->getResult();
	}

	public function findOneByIdJoinedToSubCategory($productId)
	{
	    $query = $this->getEntityManager()
	        ->createQuery(
	            'SELECT p, s FROM AppBundle:Product p
	            JOIN p.SubCategory s
	            WHERE p.id = :id'
	        )->setParameter('id', $productId);

	    try {
	        return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) {
	        return null;
	    }
	}
}
